FUNCTIONAL_GROUPS_DICT = {
    "R-tBu": "[C;D4]([C;H3])([C;H3])[C;H3]",
    "R-CF3": "[C;D4](F)(F)F",
    "R-CN": "[C;D2]#N",
    "R-C#CH": "[C;D2]#[C;H]",
    "R-NO2": "[N;D3](=O)O",
    "R-SO2NH2": "[S;D4](=O)(=O)[N;H2]",
    "R-C(=O)OCH3": "[C;D3](=O)O[C;H3]",
    "R-OEt": "[O;D2][C;H2][C;H3]",
    "R-OMe": "[O;D2][C;H3]",
    "R-SCH3": "[S;D2][C;H3]",
    "R-C(=O)N": "[C;D3](=O)N",
    "R-C(=O)CH3": "[C;D3](=O)[C;H3]",
    "R=O": "[O;D1;H0]",
    "R=S": "[S;D1]",
    "R-NH2": "[N;H2]",
    "RX": "[F,Cl,Br,I]",
    "ROH": "[O;H]",
}
