FUNCTIONAL_GROUPS_DICT = {
    "R-tBu": "[C,c]-C([C;H3])([C;H3])[C;H3]",
    "R-CF3": "[C,c]-C(F)(F)F",
    "R-CN": "[C,c]-C#N",
    "R-C#CH": "[C,c]-C#[C;H]",
    "R-NO2": "[C,c]-N(=O)O",
    "R-SO2NH2": "[C,c]-S(=O)(=O)[N;H2]",
    "R-C(=O)OCH3": "[C,c]-C(=O)O[C;H3]",
    "R-OEt": "[C,c]-O[C;H2][C;H3]",
    "R-OMe": "[C,c]-O[C;H3]",
    "R-SCH3": "[C,c]-S[C;H3]",
    "R-C(=O)NH2": "[C,c]-C(=O)[N;H2]",
    "R-C(=O)CH3": "[C,c]-C(=O)[C;H3]",
    "R=O": "C(=O)",
    "R=S": "C(=S)",
    "R-NH2": "[C,c]-[N;H2]",
    "RX": "[C,c]-[F,Cl,Br,I]",
    "ROH": "[C,c]-[O;H]",
}
